version: "3.9"

services:
  attacker:
    build: .
    hostname: attacker
    environment:
      - USERS=student:CSCI-3403!
    ports:
      - "22:22"
      - "3001-3099:3001-3099"
    volumes:
      - ./fs/etc/ssh:/etc/ssh
      - ./fs/home:/home
      - ./fs/root:/root
      - ./fs/tmp:/tmp